name: CI

on: pull_request

jobs:
  Continuous-Integration:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up python
        id: setup-python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install requirements
        run: pip install -r requirements-dev.txt

      - name: List directory contents
        run: ls -la

      - name: Usar uma secret
        env:
          db_user: ${{ secrets.db_user }}
          db_host: ${{ secrets.db_host }}
          db_pass: ${{ secrets.db_pass }}
          db_port: ${{ secrets.db_port }}
          db_name: ${{ secrets.db_name }}

      - name: Run tests
        run: pytest -v tests